"""
Django settings for tomoi project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

AUTH_USER_MODEL = 'accounts.CustomUser'

#Login with Google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '849220056035-q1d9h4ce1uhq4312q3hvjmf45ea66jna.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = 'http://localhost:8000/social-auth/complete/google-oauth2/'
SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'store:home'
SOCIAL_AUTH_LOGIN_ERROR_URL = 'store:home'

LOGIN_REDIRECT_URL = '/'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-07d6%7f4=mg5e+g89&b(ke1-oklw=^2m(9ub&4f352i9kl8$pf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'payment': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
    },
}
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'store',
    'payment',
    'social_django',
    'django_ckeditor_5',
    'colorfield',
    'admin_interface',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.EmailVerificationMiddleware',
    'accounts.middleware.RequestBodyMiddleware',
]

ROOT_URLCONF = 'tomoi.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'store.context_processors.banners',
            ],
        },
    },
]
WSGI_APPLICATION = 'tomoi.wsgi.application'

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'accounts' / 'static',
    BASE_DIR / 'store' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Thêm cấu hình này
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


SESSION_SAVE_EVERY_REQUEST = True
# Cấu hình mặc định cho session
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Sử dụng cơ sở dữ liệu để lưu session


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'  # hoặc 'store.CustomUser' nếu dùng trong store

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = 'store:home'
LOGOUT_REDIRECT_URL = 'store:home'

# Email tự động
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tomoivn2024@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'vhnl yeww apjf jaar'

# PAYPAL_MODE = 'sandbox'  # Hoặc 'live' nếu sử dụng trong môi trường thực tế
# PAYPAL_CLIENT_ID = 'your-client-id'
# PAYPAL_CLIENT_SECRET = 'your-client-secret'

# VNPay Configuration
VNPAY_CLIENT_ID = 'tomoi.vn'
VNPAY_USERNAME = 'tomoivn2024@gmail.com'
VNPAY_PASSWORD = 'Hanh2004@'
VNPAY_CLIENT_SECRET = '890-'
VNPAY_TMN_CODE = "B2RG0YSD"
VNPAY_HASH_SECRET = 'S500OYUZE6YZRFNMC2LFQZZXMXATAJKK'
VNPAY_HASH_SECRET_KEY = "S500OYUZE6YZRFNMC2LFQZZXMXATAJKK"
VNPAY_PAYMENT_URL = "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
VNPAY_RETURN_URL = "http://127.0.0.1:8000/payment/vnpay/return/"

# Cập nhật các URL return riêng biệt
VNPAY_DEPOSIT_RETURN_URL = "http://127.0.0.1:8000/accounts/deposit/vnpay-deposit-return/"
VNPAY_ORDER_RETURN_URL = "http://127.0.0.1:8000/accounts/payment/vnpay-order-return/"

# SePay Configuration
SEPAY_API_KEY = 'ZMR2Y3H54KLIZSKG0YYST8AJWCPCPN0D7KAUUXTUETG6HTOQGXL3NJDORFXZWQB1'
SEPAY_ACCOUNT = 'VQRQABHEI5230'
SEPAY_BANK = 'MBBank'

# Thêm vào cuối file
CART_SESSION_ID = 'cart'

# Thêm cấu hình cho CKEditor 5
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                   'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
        'height': '300px',
    },
}

CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
CKEDITOR_5_UPLOAD_PATH = "uploads/"

# Thêm đường dẫn cho favicon
FAVICON_PATH = STATIC_URL + 'images/favicon.ico'

# DeepL Translation API settings
DEEPL_API_KEY = '893c70b4-e735-4e1c-b9cd-e27585166d17:fx'

# DoiThe Configuration
DOITHE_PARTNER_ID = '2881917827'  # Dùng ID của API POST
DOITHE_PARTNER_KEY = '919a81fcd35df8bf1d88e65381a82baa'
DOITHE_API_URL = 'https://doithe1s.vn/chargingws/v2'  # URL API của DoiThe.vn
DOITHE_CALLBACK_URL = 'http://127.0.0.1:8000/accounts/deposit/card-callback/'
