from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('social-login/', views.social_login, name='social_login'),
    path('auth/', views.auth, name='auth'),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('send-otp/', views.send_otp, name='send_otp'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),

    path('register/verify/', views.register_verify, name='register_verify'),
    path('verify-email/<str:token>/', views.verify_email, name='verify_email'),
    path('resend-verification/', views.resend_verification, name='resend_verification'),

    path('profile/update/', views.update_profile, name='update_profile'),
    path('unauthorized/', views.unauthorized_view, name='unauthorized'),
    path('user-info/', views.user_info, name='user_info'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('user-info/payment-history/', views.payment_history, name='payment_history'),
    path('user-info/order-history/', views.order_history, name='order_history'),
    path('security/', views.security_view, name='security'),
    path('security/change-password/', views.change_password, name='change_password'),
    path('security/setup-2fa/', views.setup_2fa, name='setup_2fa'),
    path('security/setup-ga/', views.setup_google_authenticator, name='setup_ga'),
    path('security/verify-ga/', views.verify_ga, name='verify_ga'),
    path('security/delete-2fa/', views.delete_2fa, name='delete_2fa'),
    path('security/send-otp-email/', views.send_otp_email, name='send_otp_email'),
    path('security/verify-otp/', views.verify_otp, name='verify_otp'),
    path('update-email/', views.update_email, name='update_email'),
    path('send-email-change-otp/', views.send_email_change_otp, name='send_email_change_otp'),
    path('verify-email-change-otp/', views.verify_email_change_otp, name='verify_email_change_otp'),
    path('settings/', views.settings_view, name='settings'),
    path('update-language/', views.update_language, name='update_language'),
    path('set_language/', views.set_language, name='set_language'),
    path('user-info/wishlist/', views.wishlist, name='wishlist'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('resend-verification-email/', views.resend_verification_email, name='resend_verification_email'),
    path('translate/', views.translate_text, name='translate_text'),
    path('check-2fa-password/', views.check_2fa_password, name='check_2fa_password'),
    path('confirm-device/', views.confirm_device, name='confirm_device'),
    path('logout-device/', views.logout_device, name='logout_device'),
    path('security/change-2fa-password/', views.change_2fa_password, name='change_2fa_password'),
    path('security/check-2fa-status/', views.check_2fa_status, name='check_2fa_status'),
    path('security/verify-2fa-password/', views.verify_2fa_password, name='verify_2fa_password'),
    path('security/verify-device/', views.verify_device, name='verify_device'),
    path('deposit/', views.deposit_view, name='deposit'),
    path('tcoin/', views.tcoin_view, name='tcoin'),
    path('deposit/create-payment/', views.create_payment, name='create_payment'),
    path('deposit/vnpay-return/', views.vnpay_return, name='vnpay_return'),
]
