# Generated by Django 5.1.4 on 2025-01-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='require_2fa_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='require_2fa_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='require_2fa_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='require_2fa_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('password', 'Password'), ('email', 'Email OTP'), ('google', 'Google Authenticator')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
