# Generated by Django 5.1.6 on 2025-02-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_verification_token_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('pending', 'Chờ xác minh'), ('suspended', 'Ngừng hoạt động')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do ngừng hoạt động'),
        ),
    ]
