# Generated by Django 5.1.4 on 2025-03-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_account_type_customuser_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bank_account",
            field=models.CharField(
                blank=True,
                help_text="Số tài khoản ngân hàng",
                max_length=50,
                null=True,
                verbose_name="Số tài khoản",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bank_branch",
            field=models.CharField(
                blank=True,
                help_text="Chi nhánh ngân hàng",
                max_length=100,
                null=True,
                verbose_name="Chi nhánh",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="Tên ngân hàng",
                max_length=100,
                null=True,
                verbose_name="Tên ngân hàng",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_notes",
            field=models.TextField(
                blank=True,
                help_text="Ghi chú về người dùng",
                null=True,
                verbose_name="Ghi chú",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Số điện thoại"
            ),
        ),
    ]
