# Generated by Django 5.1.4 on 2025-03-07 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_bank_account_customuser_bank_branch_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="tcoin",
            new_name="tcoin_balance",
        ),
    ]
