# Generated by Django 5.1.6 on 2025-02-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ga_secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
