# Generated by Django 5.1.7 on 2025-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_tcoinhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hoạt động cuối'),
        ),
    ]
