# Generated by Django 5.1.7 on 2025-04-01 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_customuser_last_activity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="tcoin_balance",
            new_name="tcoin",
        ),
    ]
