# Generated by Django 5.1.4 on 2025-02-22 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_deposit_tcoinhistory_dailycheckin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tcoin",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CardTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=50, unique=True)),
                (
                    "telco",
                    models.CharField(
                        choices=[
                            ("VIETTEL", "Viettel"),
                            ("MOBIFONE", "Mobifone"),
                            ("VINAPHONE", "Vinaphone"),
                            ("VIETNAMOBILE", "Vietnamobile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("serial", models.CharField(max_length=50)),
                ("pin", models.CharField(max_length=50)),
                ("amount", models.IntegerField()),
                ("real_amount", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang xử lý"),
                            ("success", "Thành công"),
                            ("failed", "Thất bại"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch thẻ cào",
                "verbose_name_plural": "Giao dịch thẻ cào",
                "ordering": ["-created_at"],
            },
        ),
    ]
