# Generated by Django 5.1.7 on 2025-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_tcoin_balance_to_tcoin"),
    ]

    operations = [
        migrations.AddField(
            model_name="tcoinhistory",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("login", "Đăng nhập"),
                    ("order", "Đặt hàng"),
                    ("checkin", "Điểm danh"),
                    ("referral", "Giới thiệu"),
                    ("promotion", "Khuyến mãi"),
                    ("system", "Hệ thống"),
                    ("admin", "Quản trị viên"),
                    ("other", "Khác"),
                ],
                default="other",
                max_length=20,
                verbose_name="Loại hoạt động",
            ),
        ),
    ]
