# Generated by Django 5.1.6 on 2025-02-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_tcoin_cardtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_auth_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('password', 'Mật khẩu cấp 2'), ('email', 'Email OTP'), ('google', 'Google Authenticator')], max_length=20, null=True),
        ),
    ]
