# Generated by Django 5.1.4 on 2025-02-11 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="description",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="expired_at",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="reference_id",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("vnpay", "VNPAY"),
                    ("momo", "MoMo"),
                    ("banking", "Mobile Banking"),
                    ("balance", "Số dư"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ thanh toán"),
                    ("completed", "Đã thanh toán"),
                    ("failed", "Thất bại"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=20, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="transaction",
            table=None,
        ),
    ]
