# Generated by Django 5.1.4 on 2025-02-11 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_remove_transaction_description_and_more"),
        ("payment", "xxxx_auto_xxx"),
    ]

    operations = []
