# Generated by Django 5.1.4 on 2025-02-11 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_merge_20250211_0845"),
        ("payment", "xxxx_add_transaction_type"),
    ]

    operations = []
