# Generated by Django 5.1.6 on 2025-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_add_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('vnpay', 'VNPAY'), ('tcoin', 'TCoin'), ('momo', 'MoMo'), ('paypal', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Chờ xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Lỗi'), ('cancelled', 'Huỷ')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Mua hàng'), ('deposit', 'Nạp tiền')], max_length=20),
        ),
    ]
