# Generated by Django 5.1.4 on 2025-02-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0007_remove_transaction_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("purchase", "Mua hàng"), ("deposit", "Nạp tiền")],
                default="purchase",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[("vnpay", "VNPAY"), ("card", "Thẻ cào")],
                max_length=20,
            ),
        ),
    ]
