# Generated by Django 5.1.4 on 2025-02-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0008_transaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionitem",
            name="subtotal",
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transactionitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
