# Generated by Django 5.1.6 on 2025-02-11 23:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_wishlist_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='Mã sản phẩm'),
            preserve_default=False,
        ),
    ]
