# Generated by Django 5.1.7 on 2025-03-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_discount_allowed_users_discount_min_purchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
