# Generated by Django 5.1.4 on 2025-02-25 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_orderitem_duration_orderitem_upgrade_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_user_product_variant",
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_session_product_variant",
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={
                ("session_key", "product", "variant", "duration", "upgrade_email"),
                ("user", "product", "variant", "duration", "upgrade_email"),
            },
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="account_password",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="updated_at",
        ),
    ]
