# Generated by Django 5.1.4 on 2025-01-28 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_description_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['position', 'order']},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='location',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product'),
        ),
    ]
