# Generated by Django 5.1.4 on 2025-01-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_banner_options_remove_banner_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.IntegerField(choices=[(1, 'Banner Chính'), (2, 'Banner Phụ'), (3, 'Banner Trái'), (4, 'Banner Phải')], default=1),
        ),
    ]
