# Generated by Django 5.1.7 on 2025-04-08 01:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_supplier'),
        ('store', '0007_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_12_months',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_3_months',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_6_months',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá gốc'),
        ),
        migrations.AddField(
            model_name='product',
            name='label_type',
            field=models.CharField(blank=True, choices=[('new_account', 'Tài khoản cấp'), ('upgrade', 'Nâng cấp chính chủ')], max_length=20, null=True, verbose_name='Loại nhãn'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Từ khóa SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiêu đề SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', to='dashboard.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shared_stock_id',
            field=models.CharField(blank=True, help_text='ID để nhóm các biến thể sử dụng chung kho', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='shared_stock_id',
            field=models.CharField(blank=True, help_text='ID để nhóm các tùy chọn sử dụng chung kho', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.productattribute')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='store.productvariant')),
            ],
            options={
                'unique_together': {('variant', 'attribute')},
            },
        ),
    ]
