# Generated by Django 5.1.4 on 2025-01-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_premiumaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremiumAccount',
        ),
    ]
