# Generated by Django 5.1.4 on 2025-01-28 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_banner_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['location', 'order']},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='position',
        ),
        migrations.AddField(
            model_name='banner',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='store.bannerlocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannerlocation',
            name='code',
            field=models.CharField(choices=[('main', 'Banner Chính'), ('side', 'Banner Phụ'), ('left', 'Banner Trái'), ('right', 'Banner Phải')], max_length=50, unique=True),
        ),
    ]
