# Generated by Django 5.1.7 on 2025-04-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productvariant_options_remove_product_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('vnpay', 'VNPay'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('balance', 'Số dư tài khoản'), ('acb_qr', 'QR ACB')], max_length=20, null=True),
        ),
    ]
