# Generated by Django 5.1.4 on 2025-02-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_searchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
