# Generated by Django 5.1.4 on 2025-01-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_banner_options_remove_banner_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='location',
            field=models.CharField(choices=[('main', 'Banner Chính'), ('side1', 'Banner Phụ 1'), ('side2', 'Banner Phụ 2'), ('left', 'Banner Trái'), ('right', 'Banner Phải')], default='main', max_length=20),
        ),
        migrations.DeleteModel(
            name='BannerLocation',
        ),
    ]
