# Generated by Django 5.1.6 on 2025-03-01 00:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_is_active_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('netflix', 'Netflix'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('disney', 'Disney+'), ('apple', 'Apple TV+'), ('hbo', 'HBO GO')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.CharField(choices=[('1_DAY', '1 ngày'), ('1_WEEK', '1 tuần'), ('1_MONTH', '1 tháng'), ('3_MONTHS', '3 tháng'), ('6_MONTHS', '6 tháng'), ('12_MONTHS', '1 năm')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
