# Generated by Django 5.1.4 on 2025-03-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_remove_product_product_code_product_brand_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Phần trăm"),
                            ("fixed", "Số tiền cố định"),
                        ],
                        default="percentage",
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_uses", models.IntegerField(default=0)),
                ("used_count", models.IntegerField(default=0)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("categories", models.ManyToManyField(blank=True, to="store.category")),
                ("products", models.ManyToManyField(blank=True, to="store.product")),
            ],
            options={
                "verbose_name": "Mã giảm giá",
                "verbose_name_plural": "Mã giảm giá",
            },
        ),
    ]
