# Generated by Django 5.1.6 on 2025-03-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cảnh báo'), ('critical', 'Khẩn cấp')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thông Báo Hệ Thống',
                'verbose_name_plural': 'Các Thông Báo Hệ Thống',
                'ordering': ['-created_at'],
            },
        ),
    ]
