# Generated by Django 5.1.7 on 2025-03-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_create_apiconfig'),
        ('dashboard', '0005_event_calendarevent'),
    ]

    operations = [
    ]
