# Generated by Django 5.1.7 on 2025-03-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_merge_0002_create_apiconfig_0005_event_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfig',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chatbot/'),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='chatbot_name',
            field=models.CharField(default='TomOi Assistant', max_length=50),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='theme_color',
            field=models.CharField(default='#df2626', max_length=20),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='base_prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
