# Generated by Django 5.1.7 on 2025-03-15 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_chatbotconfig_avatar_chatbotconfig_chatbot_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='Session ID')),
                ('conversation_data', models.JSONField(default=dict, verbose_name='Dữ liệu cuộc trò chuyện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử cuộc trò chuyện',
                'verbose_name_plural': 'Lịch sử cuộc trò chuyện',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['session_id'], name='dashboard_c_session_83f064_idx'), models.Index(fields=['user'], name='dashboard_c_user_id_6c6bda_idx'), models.Index(fields=['created_at'], name='dashboard_c_created_88ad5d_idx')],
            },
        ),
    ]
