# Generated by Django 5.1.7 on 2025-03-15 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_chatbotconversation'),
        ('store', '0004_alter_orderitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên lý do')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Lý do bảo hành',
                'verbose_name_plural': 'Lý do bảo hành',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá dịch vụ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Dịch vụ bảo hành',
                'verbose_name_plural': 'Dịch vụ bảo hành',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_reason', models.TextField(blank=True, null=True, verbose_name='Lý do khác')),
                ('account_username', models.CharField(max_length=255, verbose_name='Tên đăng nhập tài khoản')),
                ('account_password', models.CharField(max_length=255, verbose_name='Mật khẩu tài khoản')),
                ('account_type', models.CharField(max_length=255, verbose_name='Loại tài khoản')),
                ('error_screenshot', models.ImageField(upload_to='warranty_screenshots/', verbose_name='Ảnh chụp lỗi')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('telegram', 'Telegram'), ('zalo', 'Zalo'), ('email', 'Email'), ('phone', 'Điện thoại'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Nền tảng liên hệ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Đã hoàn thành'), ('rejected', 'Đã từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('is_self_registered', models.BooleanField(default=False, verbose_name='Tự đăng ký')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_requests', to='store.order', verbose_name='Đơn hàng')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_requests', to='dashboard.warrantyreason', verbose_name='Lý do')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_requests', to='dashboard.source', verbose_name='Nguồn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Yêu cầu bảo hành',
                'verbose_name_plural': 'Yêu cầu bảo hành',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Đã hoàn thành'), ('rejected', 'Đã từ chối')], max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú cho khách')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú nội bộ')),
                ('warranty_types', models.JSONField(blank=True, default=list, null=True, verbose_name='Loại bảo hành')),
                ('added_days', models.IntegerField(default=0, verbose_name='Số ngày bù thêm')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số tiền hoàn trả')),
                ('new_account_info', models.JSONField(blank=True, null=True, verbose_name='Thông tin tài khoản mới')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_request_histories', to=settings.AUTH_USER_MODEL, verbose_name='Admin xử lý')),
                ('warranty_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_histories', to='dashboard.warrantyrequest', verbose_name='Yêu cầu bảo hành')),
            ],
            options={
                'verbose_name': 'Lịch sử xử lý bảo hành',
                'verbose_name_plural': 'Lịch sử xử lý bảo hành',
                'ordering': ['-created_at'],
            },
        ),
    ]
