# Generated by Django 5.1.7 on 2025-03-15 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_warrantyreason_warrantyservice_warrantyrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('source_created', 'Tạo nguồn mới'), ('source_updated', 'Cập nhật nguồn'), ('order', 'Đặt hàng'), ('availability_check', 'Kiểm tra hàng'), ('price_updated', 'Cập nhật giá'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Loại nhật ký')),
                ('has_stock', models.BooleanField(default=True, verbose_name='Có hàng')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Giá')),
                ('processing_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thời gian xử lý (phút)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian tạo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_histories', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='dashboard.source', verbose_name='Nguồn cung cấp')),
                ('source_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='dashboard.sourceproduct', verbose_name='Sản phẩm nguồn')),
            ],
            options={
                'verbose_name': 'Lịch sử nguồn',
                'verbose_name_plural': 'Lịch sử nguồn',
                'ordering': ['-created_at'],
            },
        ),
    ]
