# Generated by Django 5.1.7 on 2025-03-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_brand_productlabel_product_cross_sale_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Hình ảnh')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Liên kết')),
                ('position', models.CharField(choices=[('homepage', 'Trang chủ'), ('sidebar', 'Thanh bên'), ('product', 'Trang sản phẩm'), ('category', 'Trang danh mục'), ('other', 'Khác')], default='homepage', max_length=20, verbose_name='Vị trí hiển thị')),
                ('priority', models.IntegerField(default=10, verbose_name='Ưu tiên hiển thị')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
