# Generated by Django 5.1.7 on 2025-03-17 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='priority',
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('home_top', 'Trang chủ - Trên cùng'), ('home_middle', 'Trang chủ - Giữa trang'), ('home_bottom', 'Trang chủ - Dưới cùng'), ('sidebar', 'Sidebar'), ('category', 'Trang danh mục'), ('product', 'Trang sản phẩm')], max_length=20, verbose_name='Vị trí hiển thị'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Đường dẫn'),
        ),
    ]
