# Generated by Django 5.1.7 on 2025-03-18 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_discountusage_discount_and_more'),
        ('store', '0005_discount_allowed_users_discount_min_purchase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotconfig',
            options={'verbose_name': 'Cấu hình chatbot', 'verbose_name_plural': 'Cấu hình chatbot'},
        ),
        migrations.RemoveField(
            model_name='discounthistory',
            name='action',
        ),
        migrations.RemoveField(
            model_name='discounthistory',
            name='details',
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='apiintegration',
            name='active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='chatbotconfig',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='discounthistory',
            name='action_type',
            field=models.CharField(choices=[('create', 'Tạo mới'), ('update', 'Cập nhật'), ('delete', 'Xóa'), ('activate', 'Kích hoạt'), ('deactivate', 'Vô hiệu hóa')], default='update', max_length=20, verbose_name='Loại hành động'),
        ),
        migrations.AddField(
            model_name='discounthistory',
            name='changes_json',
            field=models.TextField(blank=True, null=True, verbose_name='Chi tiết thay đổi (JSON)'),
        ),
        migrations.AddField(
            model_name='discounthistory',
            name='discount_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Mã giảm giá'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chatbot/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='base_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='Prompt cơ bản'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='chatbot_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tên hiển thị'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Kích hoạt (cũ)'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='name',
            field=models.CharField(default='TomOi Assistant', max_length=50, verbose_name='Tên chatbot'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='rejection_message',
            field=models.TextField(default='Xin lỗi, tôi không thể trả lời câu hỏi này. Vui lòng liên hệ với nhân viên hỗ trợ.', verbose_name='Thông báo từ chối'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='theme_color',
            field=models.CharField(default='#4e73df', max_length=20, verbose_name='Màu chủ đề'),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='discounthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian thực hiện'),
        ),
        migrations.AlterField(
            model_name='discounthistory',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='store.discount'),
        ),
        migrations.AlterField(
            model_name='discounthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.CreateModel(
            name='DiscountBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên bản sao lưu')),
                ('backup_data', models.TextField(verbose_name='Dữ liệu sao lưu (JSON)')),
                ('include_usage', models.BooleanField(default=False, verbose_name='Bao gồm lịch sử sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dẫn file')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Bản sao lưu mã giảm giá',
                'verbose_name_plural': 'Bản sao lưu mã giảm giá',
                'ordering': ['-created_at'],
            },
        ),
    ]
