# Generated by Django 5.1.7 on 2025-03-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_apiconfig_api_type_alter_apiconfig_endpoint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='Session ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='User ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên người dùng')),
                ('messages', models.TextField(blank=True, null=True, verbose_name='Nội dung tin nhắn')),
                ('message_count', models.IntegerField(default=0, verbose_name='Số lượng tin nhắn')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Đánh giá')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Phản hồi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lịch sử trò chuyện',
                'verbose_name_plural': 'Lịch sử trò chuyện',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('feedback_text', models.TextField(verbose_name='Nội dung góp ý')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Góp ý chatbot',
                'verbose_name_plural': 'Góp ý chatbot',
            },
        ),
        migrations.AlterModelOptions(
            name='chatbotconversation',
            options={'verbose_name': 'Lịch sử cuộc trò chuyện', 'verbose_name_plural': 'Lịch sử cuộc trò chuyện'},
        ),
        migrations.RemoveIndex(
            model_name='chatbotconversation',
            name='dashboard_c_user_id_6c6bda_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatbotconversation',
            name='dashboard_c_created_88ad5d_idx',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatbotconversation',
            name='conversation_data',
            field=models.JSONField(verbose_name='Dữ liệu cuộc trò chuyện'),
        ),
        migrations.AlterField(
            model_name='chatbotconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatbotconversation',
            name='session_id',
            field=models.CharField(max_length=100, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='chatbotconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatbotconversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='full_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chatbotconversation',
            index=models.Index(fields=['user', 'created_at'], name='dashboard_c_user_id_fa9b66_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotlog',
            index=models.Index(fields=['session_id'], name='dashboard_c_session_4a583a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotlog',
            index=models.Index(fields=['username'], name='dashboard_c_usernam_697d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotlog',
            index=models.Index(fields=['created_at'], name='dashboard_c_created_a985b1_idx'),
        ),
        migrations.AddField(
            model_name='chatfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
