# Generated by Django 5.1.7 on 2025-03-19 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0019_alter_apiconfig_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_message_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Thời gian tin nhắn cuối"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuộc hội thoại",
                "verbose_name_plural": "Cuộc hội thoại",
                "ordering": ["-last_message_time"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Văn bản"),
                            ("image", "Hình ảnh"),
                            ("order", "Đơn hàng"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="Loại tin nhắn",
                    ),
                ),
                ("content", models.TextField(verbose_name="Nội dung tin nhắn")),
                (
                    "order_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dữ liệu đơn hàng"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Đã đọc")),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian gửi"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian đọc"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tin nhắn",
                "verbose_name_plural": "Tin nhắn",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Đã đọc")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tạo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Thông báo",
                "verbose_name_plural": "Thông báo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ChatbotLog",
        ),
        migrations.AlterModelOptions(
            name="chatbotconversation",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Lịch sử cuộc trò chuyện",
                "verbose_name_plural": "Lịch sử cuộc trò chuyện",
            },
        ),
        migrations.RemoveIndex(
            model_name="chatbotconversation",
            name="dashboard_c_user_id_fa9b66_idx",
        ),
        migrations.AlterField(
            model_name="apiconfig",
            name="model",
            field=models.CharField(
                choices=[
                    ("gemini-2.0-flash", "Gemini 2.0 Flash - Nhanh và đa chức năng"),
                    (
                        "gemini-2.0-flash-lite",
                        "Gemini 2.0 Flash-Lite - Tiết kiệm, độ trễ thấp",
                    ),
                    (
                        "gemini-2.0-pro-exp-02-05",
                        "Gemini 2.0 Pro Experimental - Mạnh mẽ nhất",
                    ),
                    ("gemini-1.5-flash", "Gemini 1.5 Flash - Nhanh và linh hoạt"),
                    (
                        "gemini-1.5-flash-8b",
                        "Gemini 1.5 Flash-8B - Cho tác vụ đơn giản",
                    ),
                    ("gemini-1.5-pro", "Gemini 1.5 Pro - Suy luận phức tạp"),
                    ("imagen-3.0-generate-002", "Imagen 3 - Tạo hình ảnh"),
                ],
                default="gemini-1.5-flash",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="chatbotconversation",
            name="conversation_data",
            field=models.JSONField(
                default=dict, verbose_name="Dữ liệu cuộc trò chuyện"
            ),
        ),
        migrations.AlterField(
            model_name="chatbotconversation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời gian tạo"),
        ),
        migrations.AlterField(
            model_name="chatbotconversation",
            name="session_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Session ID"
            ),
        ),
        migrations.AlterField(
            model_name="chatbotconversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Cập nhật lần cuối"),
        ),
        migrations.AlterField(
            model_name="chatbotconversation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatbot_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotconversation",
            index=models.Index(fields=["user"], name="dashboard_c_user_id_6c6bda_idx"),
        ),
        migrations.AddIndex(
            model_name="chatbotconversation",
            index=models.Index(
                fields=["created_at"], name="dashboard_c_created_88ad5d_idx"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Quản trị viên",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="dashboard.conversation",
                verbose_name="Cuộc hội thoại",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người nhận",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người gửi",
            ),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.message",
                verbose_name="Tin nhắn",
            ),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("admin", "user")},
        ),
    ]
