# Generated by Django 5.1.7 on 2025-04-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0020_conversation_message_usernotification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="apiconfig",
            name="model",
            field=models.CharField(
                choices=[
                    ("gemini-2.0-flash", "Gemini 2.0 Flash - Nhanh và đa chức năng"),
                    (
                        "gemini-2.0-flash-lite",
                        "Gemini 2.0 Flash-Lite - Tiết kiệm, độ trễ thấp",
                    ),
                    (
                        "gemini-2.0-pro-exp-02-05",
                        "Gemini 2.0 Pro Experimental - Mạnh mẽ nhất",
                    ),
                    ("gemini-1.5-flash", "Gemini 1.5 Flash - Nhanh và linh hoạt"),
                    (
                        "gemini-1.5-flash-8b",
                        "Gemini 1.5 Flash-8B - Cho tác vụ đơn giản",
                    ),
                    ("gemini-1.5-pro", "Gemini 1.5 Pro - Suy luận phức tạp"),
                    ("imagen-3.0-generate-002", "Imagen 3 - Tạo hình ảnh"),
                ],
                default="gemini-2.0-flash",
                max_length=100,
            ),
        ),
    ]
