# Generated by Django 5.1.7 on 2025-04-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_productattribute_alter_brand_options_brand_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thời hạn')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('value', models.CharField(max_length=20, unique=True, verbose_name='Giá trị')),
                ('days', models.PositiveIntegerField(verbose_name='Số ngày')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thời hạn sản phẩm',
                'verbose_name_plural': 'Thời hạn sản phẩm',
                'ordering': ['display_order', 'days'],
            },
        ),
    ]
