# Generated by Django 5.1.7 on 2025-04-07 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_productduration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Giá trị thuộc tính', 'verbose_name_plural': 'Giá trị thuộc tính'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Thuộc tính sản phẩm', 'verbose_name_plural': 'Thuộc tính sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'Giá trị thuộc tính sản phẩm', 'verbose_name_plural': 'Giá trị thuộc tính sản phẩm'},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='slug',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='dashboard.productattribute'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên thuộc tính'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_values', to='dashboard.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_values', to='dashboard.product'),
        ),
    ]
