# Generated by Django 5.1.7 on 2025-04-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhà cung cấp')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã nhà cung cấp')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người liên hệ')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('status', models.CharField(choices=[('active', 'Đang hợp tác'), ('inactive', 'Ngừng hợp tác'), ('pending', 'Đang đàm phán')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(choices=[('bank', 'Chuyển khoản ngân hàng'), ('cash', 'Tiền mặt'), ('credit', 'Công nợ'), ('other', 'Khác')], default='bank', max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_term', models.IntegerField(default=0, help_text='Số ngày thanh toán', verbose_name='Kỳ hạn thanh toán')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['name'],
            },
        ),
    ]
