# Generated by Django 5.1.7 on 2025-04-09 15:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_activitylog'),
        ('store', '0010_product_sold_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyrequest',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='warrantyrequest',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='platform',
            field=models.CharField(choices=[('netflix', 'Netflix'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('disney', 'Disney+'), ('apple', 'Apple TV+'), ('hbo', 'HBO GO')], max_length=20, verbose_name='Nền tảng'),
        ),
        migrations.AlterField(
            model_name='source',
            name='product_type',
            field=models.CharField(max_length=50, verbose_name='Loại sản phẩm'),
        ),
        migrations.AlterField(
            model_name='sourcelog',
            name='log_type',
            field=models.CharField(choices=[('check', 'Kiểm tra'), ('purchase', 'Mua hàng'), ('error', 'Lỗi')], max_length=20, verbose_name='Loại log'),
        ),
        migrations.AlterField(
            model_name='sourcelog',
            name='processing_time',
            field=models.IntegerField(default=0, help_text='Thời gian xử lý (giây)', verbose_name='Thời gian xử lý (giây)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourcelog',
            name='source_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.sourceproduct', verbose_name='Sản phẩm nguồn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sourceproduct',
            name='error_rate',
            field=models.IntegerField(default=0, verbose_name='Tỷ lệ lỗi (%)'),
        ),
        migrations.AlterField(
            model_name='sourceproduct',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sản phẩm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='account_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='account_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='account_username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='custom_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='error_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='warranty/screenshots/'),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='is_self_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='platform',
            field=models.CharField(choices=[('netflix', 'Netflix'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('disney', 'Disney+'), ('apple', 'Apple TV+'), ('hbo', 'HBO GO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.warrantyreason'),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.source'),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warrantyrequesthistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('rejected', 'Từ chối'), ('cancelled', 'Đã hủy')], max_length=20, verbose_name='Trạng thái'),
        ),
    ]
