# Generated by Django 5.1.7 on 2025-04-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_warrantyrequest_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TomOi', max_length=100, verbose_name='Tên website')),
                ('site_description', models.TextField(blank=True, verbose_name='Mô tả website')),
                ('site_url', models.URLField(default='https://tomoi.vn', verbose_name='URL website')),
                ('contact_email', models.EmailField(default='contact@tomoi.vn', max_length=254, verbose_name='Email liên hệ')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Favicon')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('vnpay_merchant_id', models.CharField(blank=True, max_length=100, verbose_name='VNPay Merchant ID')),
                ('vnpay_hash_secret', models.CharField(blank=True, max_length=100, verbose_name='VNPay Hash Secret')),
                ('vnpay_api_url', models.URLField(blank=True, default='https://sandbox.vnpayment.vn/paymentv2/vpcpay.html', verbose_name='VNPay API URL')),
                ('acb_merchant_id', models.CharField(blank=True, max_length=100, verbose_name='ACB Merchant ID')),
                ('acb_secret_key', models.CharField(blank=True, max_length=100, verbose_name='ACB Secret Key')),
                ('acb_api_url', models.URLField(blank=True, default='https://sandbox.acbpay.vn/api', verbose_name='ACB API URL')),
                ('paypal_client_id', models.CharField(blank=True, max_length=100, verbose_name='PayPal Client ID')),
                ('paypal_client_secret', models.CharField(blank=True, max_length=100, verbose_name='PayPal Client Secret')),
                ('paypal_mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10, verbose_name='PayPal Mode')),
                ('smtp_host', models.CharField(blank=True, max_length=100, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_username', models.CharField(blank=True, max_length=100, verbose_name='SMTP Username')),
                ('smtp_password', models.CharField(blank=True, max_length=100, verbose_name='SMTP Password')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Sử dụng TLS')),
                ('default_from_email', models.EmailField(blank=True, max_length=254, verbose_name='Email gửi mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Cài đặt hệ thống',
                'verbose_name_plural': 'Cài đặt hệ thống',
            },
        ),
    ]
